# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.12-slim

WORKDIR /app

COPY pyproject.toml README.md server.py uv.lock /app/

RUN pip install --no-cache-dir .

EXPOSE 8123

CMD ["uvicorn", "server:mcp.streamable_http_app", "--host", "0.0.0.0", "--port", "${PORT:-8123}"]
